FROM python:3.6-slim

# Prepare OS
RUN apt-get update && \
    apt-get install -y gcc linux-headers-amd64 && \
    apt-get install -y git python3-pip &&  \
    rm -rf /var/lib/apt/lists/*

# Install requirements
RUN pip3 install awscli --upgrade

COPY aws /root/.aws
RUN chown -R root:root /root/.aws
COPY ./scripts/build_model_docker_entrypoint.sh /entrypoint.sh

CMD ["/entrypoint.sh", "gl-ml-training-data", "gl-ml-training-models"]
